### ISSUE TITLE
Use with JDK1.7

### ISSUE THREAD

**Issue by kageiit** [mmc41/VALJOGen#1]
Is it possible to make this work with javac in JDK1.7 ? I am trying to use this for and android project and android does not support JDK 8 yet.

**Comment by mmc41** [comment]
The VALJOGen annotation processor needs a Java 1.8 JDK to run, but the code produced that you need to deploy on Android runs on JDK1.7 (and if you override equals, hash, and compareTo methods in a custom template you can also get the produced code to run on earlier JDK's). So it might work for you already depending on how you setup your dev environment.
